### PR TITLE
Exit early in wysiwygarea's `onDomReady` if it was destroyed

### PR DESCRIPTION
**Pull request by bantic**
The call to `onDomReady` is scheduled using `setTimeout` which creates
a potential race condition. It's possible for the editor to be torn down
in between the schedule of the call and the actual call. When that happens
this code path eventually errors because `this.editor` is undefined.

This fixes the issue described in #9451

### CODE REVIEW

**Review by cyril-sf — COMMENTED** [review]
I've used `editor.status === 'destroyed'` in the other PRs (#3 and #5).

Not sure if we want to stay consistent.

**Comment by bantic** [comment]
@cyril-sf 	They are different things. In this case we have an "editable", not an editor.

Editors don't have a status of 'detached' (https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#property-status), but editables do: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editable.html#property-status

**Comment by cyril-sf** [comment]
I know, but the editor is also available based on the next line `var editor = this.editor`.
I'm mostly not sure about the lifecycle of the `editable` object. 

It's not necessarily blocking, I'm mostly wondering if it covers the same thing.

**Review by mixonic — APPROVED** [review]

**Comment by bantic** [comment]
> I know, but the editor is also available based on the next line var editor = this.editor.

@cyril-sf 	see the comments in https://github.com/Addepar/Iverson/pull/9452. When `this.status === 'detached'` (editable status), `this.editor === undefined`. I suppose I could also check for if this.editor is undefined, but checking the editable status seems like the right thing to do here.

**Review by cyril-sf — APPROVED** [review]

**Comment by ChangXiaoning** [comment]
Hi @bantic 
I am curious about this issue. I understand this race condition happens when the editor is torn down before the execution of the function 'onDomReady' (because the function 'onDomReady' is called by 'setTimeout'). I wonder how the edior tearing down sets the editor to undefined. I inspect the destroy method of CKEDITOR.editor class in file /core/editor.js, but cannot understand how the editor is set to undefined. Could you please give me any clues? Look forwords to your reply. Thx :)

**Comment by ChangXiaoning** [comment]
@bantic 
I suspect the editor is set to undefined at the last statement of destroy method, CKEDITOR.fire( 'instanceDestroyed', null, this ), i.e., Line 787 in /core/editor.js. Otherwise, this will be undefined. The listener for instnaceDestroyed event is defined in /core/ckeditor.js. Since I am a green hand for Node.js, I am not sure why don't you just code 'CKEDITOR.fire( 'instanceDestroyed');', how does the other two parameter use? Thx :)

**Comment by ChangXiaoning** [comment]
@bantic 
I suspect the editor is set to undefined at the last statement of destroy method, CKEDITOR.fire( 'instanceDestroyed', null, this ), i.e., Line 787 in /core/editor.js. Otherwise, this will be undefined. The listener for instnaceDestroyed event is defined in /core/ckeditor.js.  However, why to pass null and this (the editor) to the fire the 'instanceDestroyed' event?

**Comment by bantic** [comment]
@ChangXiaoning Hello 👋. I'm not sure why that happens, unfortunately. It's worth pointing out that this may no longer be an issue on the main branch of ckeditor — we just noticed it on our fork here, which is hundreds of commits behind the main branch.

> However, why to pass null and this (the editor) to the fire the 'instanceDestroyed' event?

I'm not sure, but it may be worth pointing out that the 2nd argument `null` is the "data" argument to `fire()` — my understanding is that just means it is firing 'instanceDestroyed' with no data (`null`) and the instance (`this`) that is being destroyed.

**Comment by ChangXiaoning** [comment]
@bantic 
Thanks a lot for your reply. Your answer still helps me a lot. Have a good day :)

**Pull request merged**
