### PR TITLE
Revert "[hotfix] Backported the security fix from 4.4.8 release"

### PR DESCRIPTION
**Pull request by cyril-sf**
This reverts commit 4f8d1796b4fe006b53b4c68234cf2b012c975069.

We should cherry-pick commits and not recreate some that are already existing in the original repo (otherwise it makes upgrading harder)

### CODE REVIEW

**Comment by cyril-sf** [comment]
@jordansmith42 @viyatb

**Comment by cyril-sf** [comment]
@sreenath-are

**Comment by sreenath-are** [comment]
lgtm

**Comment by sreenath-are** [comment]
let's release this at the same time as https://github.com/Addepar/ckeditor-dev/pull/11, though

**Pull request merged**
